FROM node:lts-slim as builder

WORKDIR /usr/src/app

COPY package*.json package-lock.json ./
RUN npm install

COPY . .

RUN npm run build

FROM node:lts-slim

WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/dist ./dist
COPY --from=builder /usr/src/app/node_modules ./node_modules

EXPOSE ${BACKEND_PORT}
CMD ["npm", "run", "start:prod"]